content:
  -
    type: p
    innerHTML: Are you sure to delete?
  -
    type: p
    innerHTML:
      -
        type: button
        attribute:
          class: btn btn-warning
          ws_p_id: 'globals:sys/settings/plugin/wshop/editor_v1/product/id'
          onclick: "PluginWfAjax.callbackjson('product_delete/ws_p_id/'+this.getAttribute('ws_p_id'));"
        innerHTML: Yes
      -
        type: button
        attribute:
          class: btn btn-default
          data-dismiss: modal
        innerHTML: No
      